# Generated by Django 4.2.8 on 2024-05-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_review_like'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_review',
            field=models.ManyToManyField(related_name='user_like_review', to='movies.review'),
        ),
    ]
