# Generated by Django 4.2.8 on 2024-05-17 08:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nickname_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to=accounts.models.profile_image_path),
        ),
    ]
