# Generated by Django 4.2.8 on 2024-05-19 11:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default_image.jpg', upload_to=accounts.models.profile_image_path),
        ),
    ]
