# Generated by Django 4.2.8 on 2024-05-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_review',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
