# Generated by Django 4.2.8 on 2024-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(),
        ),
    ]
