# Generated by Django 4.2.8 on 2024-05-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
    ]
